package com.atguigu.front.bean;

public class TAdminRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role.id
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role.adminid
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role.roleid
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role.id
     *
     * @return the value of t_admin_role.id
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role.id
     *
     * @param id the value for t_admin_role.id
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role.adminid
     *
     * @return the value of t_admin_role.adminid
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role.adminid
     *
     * @param adminid the value for t_admin_role.adminid
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role.roleid
     *
     * @return the value of t_admin_role.roleid
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role.roleid
     *
     * @param roleid the value for t_admin_role.roleid
     *
     * @mbg.generated Fri Jun 21 20:46:39 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}