package com.atguigu.front.bean;

public class TPermissionResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_resource.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_resource.resourceid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_resource.permissionid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission_resource.id
     *
     * @return the value of t_permission_resource.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission_resource.id
     *
     * @param id the value for t_permission_resource.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission_resource.resourceid
     *
     * @return the value of t_permission_resource.resourceid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission_resource.resourceid
     *
     * @param resourceid the value for t_permission_resource.resourceid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission_resource.permissionid
     *
     * @return the value of t_permission_resource.permissionid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission_resource.permissionid
     *
     * @param permissionid the value for t_permission_resource.permissionid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}