package com.atguigu.front.bean;

public class TPermissionMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_menu.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_menu.menuid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_menu.permissionid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission_menu.id
     *
     * @return the value of t_permission_menu.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission_menu.id
     *
     * @param id the value for t_permission_menu.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission_menu.menuid
     *
     * @return the value of t_permission_menu.menuid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission_menu.menuid
     *
     * @param menuid the value for t_permission_menu.menuid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission_menu.permissionid
     *
     * @return the value of t_permission_menu.permissionid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission_menu.permissionid
     *
     * @param permissionid the value for t_permission_menu.permissionid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}