package com.atguigu.front.bean;

public class TProjectImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_images.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_images.projectid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_images.imgurl
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_images.imgtype
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    private Byte imgtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_images.id
     *
     * @return the value of t_project_images.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_images.id
     *
     * @param id the value for t_project_images.id
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_images.projectid
     *
     * @return the value of t_project_images.projectid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_images.projectid
     *
     * @param projectid the value for t_project_images.projectid
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_images.imgurl
     *
     * @return the value of t_project_images.imgurl
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_images.imgurl
     *
     * @param imgurl the value for t_project_images.imgurl
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_images.imgtype
     *
     * @return the value of t_project_images.imgtype
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public Byte getImgtype() {
        return imgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_images.imgtype
     *
     * @param imgtype the value for t_project_images.imgtype
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    public void setImgtype(Byte imgtype) {
        this.imgtype = imgtype;
    }
}