#项目名
spring:
  application:
    name: artcrowdfunding-user
    #配数据源
  datasource:
    username: root
    url: jdbc:mysql://192.168.59.132:3306/atcrowdfunding
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
  redis:
    host: 192.168.59.132
#sms的更改信息
sms:
  host: http://cowsms.market.alicloudapi.com
  path: /intf/smsapi
  method: GET
  appcode: cebece419ed6479095d0051ebd079a64

#日志打印
logging:
  level:
    com:
      atguigu: debug
#端口号
server:
  port: 7000

#注册中心
eureka:
  instance:
    hostname: localhost
    #使用ip注册上去
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

#说明mybatis配置文件位置
