package com.atguigu.user.dao;

import java.util.List;

import com.atguigu.front.bean.TCert;
import com.atguigu.front.bean.TCertExample;
import org.apache.ibatis.annotations.Param;

public interface TCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    long countByExample(TCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByExample(TCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insert(TCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insertSelective(TCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    List<TCert> selectByExample(TCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    TCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TCert record, @Param("example") TCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExample(@Param("record") TCert record, @Param("example") TCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKeySelective(TCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKey(TCert record);
}