package com.atguigu.user.dao;

import java.util.List;

import com.atguigu.front.bean.TMemberAddress;
import com.atguigu.front.bean.TMemberAddressExample;
import org.apache.ibatis.annotations.Param;

public interface TMemberAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    long countByExample(TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByExample(TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insert(TMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insertSelective(TMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    List<TMemberAddress> selectByExample(TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    TMemberAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMemberAddress record, @Param("example") TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExample(@Param("record") TMemberAddress record, @Param("example") TMemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKeySelective(TMemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKey(TMemberAddress record);
}