package com.atguigu.user.dao;

import java.util.List;

import com.atguigu.front.bean.TMemberProjectFollow;
import com.atguigu.front.bean.TMemberProjectFollowExample;
import org.apache.ibatis.annotations.Param;

public interface TMemberProjectFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    long countByExample(TMemberProjectFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByExample(TMemberProjectFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insert(TMemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insertSelective(TMemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    List<TMemberProjectFollow> selectByExample(TMemberProjectFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    TMemberProjectFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMemberProjectFollow record, @Param("example") TMemberProjectFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExample(@Param("record") TMemberProjectFollow record, @Param("example") TMemberProjectFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKeySelective(TMemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKey(TMemberProjectFollow record);
}