package com.atguigu.user.dao;

import java.util.List;

import com.atguigu.front.bean.TMemberCert;
import com.atguigu.front.bean.TMemberCertExample;
import org.apache.ibatis.annotations.Param;

public interface TMemberCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    long countByExample(TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByExample(TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insert(TMemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insertSelective(TMemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    List<TMemberCert> selectByExample(TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    TMemberCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMemberCert record, @Param("example") TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExample(@Param("record") TMemberCert record, @Param("example") TMemberCertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKeySelective(TMemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKey(TMemberCert record);
}