package com.atguigu.user.dao;

import java.util.List;

import com.atguigu.front.bean.TMember;
import com.atguigu.front.bean.TMemberExample;
import org.apache.ibatis.annotations.Param;

public interface TMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    long countByExample(TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByExample(TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insert(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insertSelective(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    List<TMember> selectByExample(TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    TMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMember record, @Param("example") TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExample(@Param("record") TMember record, @Param("example") TMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKeySelective(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKey(TMember record);
}