package com.atguigu.user.dao;

import java.util.List;

import com.atguigu.front.bean.TMessage;
import com.atguigu.front.bean.TMessageExample;
import org.apache.ibatis.annotations.Param;

public interface TMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    long countByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insert(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int insertSelective(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    List<TMessage> selectByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    TMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMessage record, @Param("example") TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByExample(@Param("record") TMessage record, @Param("example") TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKeySelective(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Thu Jun 20 11:03:52 CST 2019
     */
    int updateByPrimaryKey(TMessage record);
}