package com.atguigu.project.dao;

import com.atguigu.front.bean.TProjectImages;
import com.atguigu.front.bean.TProjectImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProjectImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    long countByExample(TProjectImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int deleteByExample(TProjectImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int insert(TProjectImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int insertSelective(TProjectImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    List<TProjectImages> selectByExample(TProjectImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    TProjectImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") TProjectImages record, @Param("example") TProjectImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByExample(@Param("record") TProjectImages record, @Param("example") TProjectImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByPrimaryKeySelective(TProjectImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_images
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByPrimaryKey(TProjectImages record);
}