package com.atguigu.project.dao;

import com.atguigu.front.bean.TReturn;
import com.atguigu.front.bean.TReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    long countByExample(TReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int deleteByExample(TReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int insert(TReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int insertSelective(TReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    List<TReturn> selectByExample(TReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    TReturn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") TReturn record, @Param("example") TReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByExample(@Param("record") TReturn record, @Param("example") TReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByPrimaryKeySelective(TReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Fri Jun 21 20:46:40 CST 2019
     */
    int updateByPrimaryKey(TReturn record);
}