#注册中心
eureka:
  instance:
    hostname: localhost
    #使用ip注册上去
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
server:
  port: 10000

spring:
  application:
    name: atcrowdfunding-app
  thymeleaf:
    cache: false
